version: '3.8'
services:
  # Application
  app:
    build:
      context: ./
      dockerfile: docker-app.dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker.xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - type: bind
        source: /c/Users/pstlemelin/.ssh/docker_rsa.pub
        target: /root/.ssh/id_rsa.pub
      - type: bind
        source: /c/Users/pstlemelin/.ssh/docker_rsa
        target: /root/.ssh/id_rsa
    depends_on:
      - database
    environment:
      XDEBUG_MODE: debug
      XDEBUG_CONFIG: client_host=host.docker.internal client_port=9003
      TZ: America/Toronto
    expose :
      - 9003
  # Web Server
  web:
    build:
      context: .
      dockerfile: docker-web.dockerfile
    links:
      - database
    working_dir: /var/www
    volumes:
      - ./:/var/www
    depends_on:
      - "app"
    ports:
      - 8000:80
  # Database
    environment:
      XDEBUG_MODE: debug
      XDEBUG_CONFIG: client_host=host.docker.internal client_port=9003
      TZ: America/Toronto
  database:
    image: mysql:8
    container_name: db
    env_file: .env
    volumes:
      - lepad-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      TZ: America/Toronto
    ports:
      - 33061:3306
  # Database management
  pma:
    image: phpmyadmin:5.1
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=${DB_HOST}
      - PMA_USER=${DB_USERNAME}
      - PMA_PASSWORD=${DB_PASSWORD}
      - PMA_PORT=${DB_PORT}
    depends_on:
      - database
    ports:
      - 8888:80
  # Mailing Server
  # mailhog:
  #   image: mailhog/mailhog
  #   logging:
  #     driver: 'none'
  #   ports:
  #     - 1025:1025
  #     - 8025:8025
volumes:
  lepad-data:
